### ISSUE TITLE
About Permission

### ISSUE THREAD

**Issue by AKflower** [AKflower/Shub#18]
### Tổng quan vấn đề
Các permission đang bị nhập nhằng và chồng lấn nhau, cần làm gọn hơn và sử dụng thêm thuộc tính phụ để phân loại scope mà quyền có tác dụng.

### Phân loại permission
**scope**: Vùng ảnh hưởng:
Sử dụng trường isGlobal: boolean trong role để phân biệt

- true: Trên toàn tổ chức

- false: Trên tổ chức của mình

**permission_1**: Quản lý người dùng:

- Tạo, chỉnh sửa người dùng.
- Tạo xóa role
- Thêm permission cho role

**permission_2**: Quản lý tài liệu (Giống permission_4 cũ):

- Thao tác tài liệu, folder của mình.

**permission_3**: Quyền truy cập

- Có quyền truy cập người dùng có role_level thấp hơn và được gán cho mình. Thay đổi so với lower-access document ở điểm không thể xem tất cả những người có level thấp hơn mà chỉ xem được của những thành viên được chỉ định cụ thể, tạm gọi là **cấp dưới trực thuộc** của người đó =>  Trong phần chỉnh sửa thông tin người dùng có thêm chức năng gán cấp dưới để permission_1 + (scope_1 /scope_2+ cùng tổ chức) thao tác, còn người dùng chỉ được xem ai là cấp dưới của mình nếu chỉ có permission_3 mà không có permission_1. 

Trường hợp đặc biệt: 

### Task
@AKflower 

- [x] Cấu trúc dữ liệu user có thêm trường **subordinates**: String[] chứa id của các user là cấp dưới
- [x] Tạo smartcontract cập nhật subordinates.
- [x] Tạo smartcontract + API lấy danh sách các user có level thấp hơn trong tổ chức
- [ ] Trường hợp đặc biệt, subordinates = ["*"] nghĩa là toàn bộ người dùng có level thấp hơn đều thuộc cấp dưới của người dùng đó -> cái này tạm thời chỉ có admin có.

@danisolation Dan

- [ ] Thêm chức năng gán, hủy gán, hiển thị cấp dưới
- [ ] Sửa lại những chỗ dùng permission cũ
