### ISSUE TITLE
Thiết kế hệ thống

### ISSUE THREAD

**Issue by AKflower** [AKflower/Shub#5]
## Description
Hệ thống còn sơ sài, luồng thực thi chưa được làm rõ, tính khả thi và tin cậy chưa cao.

## Task
- [ ] Luồng thực thi của tất cả tính năng
- [ ] Đánh giá bảo mật
- [ ] Vẽ sơ đồ

***Assign:*** @danisolation @AKflower
